name: Cypress Tests in Tesults

on:
  push:
    branches:
      - main
jobs:
  cypress-chrome-tests:
        runs-on: ubuntu-latest
        container:
          image: cypress/browsers:node-20.9.0-chrome-118.0.5993.88-1-ff-118.0.2-edge-118.0.2088.46-1
          options: --user 1001
        steps:
          - name: Get Code
            uses: actions/checkout@v4.1.5
    
          - name: Instalando dependências	
            run: npm install

          - name: Iniciando servidor local
            run: npm run dev
    
          - name: Rodando testes E2E
            run: npx cypress run